name: Build Native Image and Push to GHCR

on: [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
          
      - name: Access-Rights for maven execution
        run: chmod +x mvnw

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Login with a Repository Secret with a Token with Access to GitHub Packages
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build and Push Native Image over Maven-Wrapper
      # Native Image → -Dquarkus.native.container-build=true
      - name: Build with Maven
        run: ./mvnw package -Pnative -Dquarkus.container-image.push=true -Dquarkus.container-image.group=hftm-inf -DskipTests